/* ============================================================
   Community Resources data + labels
   Agency information was originally drawn from the Pinellas Interagency
   Networking Council for Students (PINCS) Transition Services Resource
   Guide (Sept 2015).
   Last reviewed: 2026-06-22 (Study Group verification pass: all 7 batches
   reviewed; corrections, removals, and counseling additions applied).
   Removed this pass: St. Petersburg College Disability Resources (competing
   college, off-message for PTC students), ZVRS, Williams Syndrome
   Association, Sunrise Community, Raising Down Syndrome Foundation. VSA
   Florida replaced by its successor, Arts4All Florida. Held out pending a
   working local contact: SEDNET / Pinellas (see note at the bottom of the
   array). To update an agency, edit it here. All spoke pages read from this file.
   ============================================================ */

const AGENCIES = [
  {
    name: "Agency for Persons with Disabilities (APD)",
    address: "1313 N Tampa Street, Suite 515, Tampa, FL 33602",
    phone: "813-233-4300",
    website: "https://www.apdcares.org",
    hours: "M-F 8:00 am to 5:00 pm",
    fees: "No charge or co-payment for services.",
    summary: "Florida state agency that helps people with developmental disabilities, including autism, cerebral palsy, intellectual disabilities, and Down syndrome, live, learn, and work in their community. Services are free.",
    eligibility: "Must live in Florida, be at least three years old, and have a developmental disability that occurred before age 18. Children at risk of being diagnosed may also be served.",
    intake: "Download an application from apdcares.org or contact the APD regional office.",
    tags: ["ese", "job", "learn", "transport", "independent", "talk", "medical", "day", "rec", "family", "autism"],
    verified: "2026-06"
  },
  {
    name: "Johns Hopkins All Children's Hospital",
    address: "501 6th Ave S, St. Petersburg, FL 33701",
    phone: "727-767-2886",
    website: "https://www.hopkinsallchildrens.org",
    hours: "M-F 8:00 am to 4:00 pm",
    fees: "CMS, private insurance, private pay.",
    summary: "Hospital programs that diagnose and treat autism (ages birth to 10) and other developmental conditions including learning disabilities, ADHD, motor delays, and developmental delays (ages birth to 15). Takes insurance, CMS, and private pay. Serves mainly families and K-12 students.",
    eligibility: "Birth to age 15 depending on program.",
    intake: "Call for an appointment or request one through the hospital website.",
    tags: ["ese", "esol", "medical", "talk", "family", "autism"],
    verified: "2026-06"
  },
  {
    name: "Boley Centers, Inc.",
    address: "445 31st Street North, St. Petersburg, FL 33713",
    phone: "727-821-4819",
    intakePhone: "727-499-2352",
    website: "https://www.boleycenters.org",
    hours: "M-F 8:30 am to 4:30 pm",
    fees: "Based on income. Medicare and Medicaid accepted.",
    summary: "Non-profit that helps people living with mental illness, homelessness, or other barriers in Pinellas, Hillsborough, and Manatee counties. Offers job training, supported jobs, housing, and case management.",
    eligibility: "Evaluations required for clients with disabilities.",
    intake: "Call admissions at 727-499-2352.",
    tags: ["ese", "reentry", "job", "independent", "talk", "advocacy"],
    verified: "2026-06"
  },
  {
    name: "CareerSource Tampa Bay (formerly CareerSource Pinellas)",
    address: "Pinellas centers: Gulf to Bay, 2312 Gulf to Bay Blvd, Clearwater, FL 33765; St. Petersburg, 3420 8th Avenue South, St. Petersburg, FL 33711; Tarpon Springs, 682 E Klosterman Road, Tarpon Springs, FL 34689.",
    phone: "727-524-4344",
    website: "https://careersourcetampabay.com",
    hours: "M-F 8:00 am to 5:00 pm",
    fees: "None",
    summary: "The Tampa Bay region's workforce board, serving Pinellas and Hillsborough counties. A one-stop for job seekers that helps people with disabilities find jobs, learn job skills, attend hiring events, and use Social Security's Ticket to Work program. Ask for the Disability Resource Coordinator. Services are free.",
    eligibility: "Workers with disabilities entering or returning to the workforce. Ticket to Work or WIOA eligibility needed for vocational or post-secondary training.",
    intake: "Call 727-524-4344 or visit a Pinellas center. For Social Security Ticket to Work, see careersourcetampabay.com/persons-with-disabilities.",
    tags: ["ese", "reentry", "job", "learn"],
    verified: "2026-06"
  },
  {
    name: "Center for Autism and Related Disabilities (CARD-USF)",
    address: "13301 Bruce B. Downs Blvd., Tampa, FL 33612",
    phone: "813-974-2532",
    website: "https://card-usf.fmhi.usf.edu",
    hours: "M-F 8:30 am to 5:00 pm",
    fees: "None",
    summary: "Free help for people with autism and related disabilities, their families, and the teachers and professionals who work with them. Offers training, coaching, and one-on-one consultation. Based at USF.",
    eligibility: "Diagnosis of Autism Spectrum Disorder or related disability (including dual sensory impairment).",
    intake: "Call for an appointment.",
    tags: ["ese", "esol", "autism", "family", "talk"],
    verified: "2026-06"
  },
  {
    name: "Creative Clay",
    address: "1846 1st Avenue South, St. Petersburg, FL 33712",
    phone: "727-825-0515",
    website: "https://www.creativeclay.org",
    email: "admin@creativeclay.org",
    hours: "M-F 9:00 am to 4:00 pm",
    fees: "Varies",
    summary: "Art studio in St. Pete for artists with developmental, physical, or emotional disabilities. Offers art classes, vocational training, summer camps for kids, and a gallery where members sell their work. Open to adults and youth ages 6 to 22.",
    eligibility: "Varies by program. Includes adults with disabilities and youth ages 6-22.",
    intake: "Telephone for instructions.",
    tags: ["ese", "job", "learn", "rec", "day"],
    verified: "2026-06"
  },
  {
    name: "211 Tampa Bay Cares (First Contact)",
    address: "Serves Pinellas County. Phone and online help; no walk-in needed.",
    phone: "211 (or 727-210-4211)",
    website: "https://211tampabay.org",
    hours: "24 hours a day, 7 days a week",
    fees: "None",
    summary: "Free, confidential help line for Pinellas County. In Pinellas, dialing 211 reaches 211 Tampa Bay Cares, which connects callers to local services for food, housing, utilities, counseling, crisis support, and more. You can also call or text.",
    eligibility: "Anyone in Pinellas County.",
    intake: "Call or text 211, or 727-210-4211.",
    tags: ["talk", "money", "family", "esol"],
    verified: "2026-06"
  },
  {
    name: "Crisis Center of Tampa Bay",
    address: "One Crisis Center Plaza, Tampa, FL 33613",
    phone: "813-234-1234 (24-hour helpline)",
    website: "https://www.crisiscenter.com",
    hours: "24 hours a day, 365 days a year",
    fees: "None",
    summary: "Free 24-hour help for anyone in a crisis: abuse, domestic violence, money problems, substance use, medical emergencies, or thoughts of suicide. Note: in Pinellas County, dialing 211 reaches 211 Tampa Bay Cares, not the Crisis Center (which is Hillsborough County's 211 provider). For suicide or mental health crisis anywhere, call or text 988.",
    eligibility: "Anyone in crisis.",
    intake: "Call the 24-hour helpline at 813-234-1234, or 988 for the Suicide and Crisis Lifeline.",
    tags: ["talk"],
    verified: "2026-06"
  },
  {
    name: "Department of Juvenile Justice (Probation and Community Intervention)",
    address: "955 26th Street South, St. Petersburg, FL 33712",
    phone: "727-893-2077",
    website: "https://www.djj.state.fl.us/programs-facilities/probation-programs",
    hours: "M-F 8:00 am to 5:00 pm",
    fees: "Varies with type of service.",
    summary: "For youth under 18 who have been charged with a crime in Pinellas County. Offers prevention, intervention, and residential programs based on a youth assessment.",
    eligibility: "Youth under age 18 charged with a law violation in Pinellas County.",
    intake: "Agency will notify family.",
    tags: ["reentry", "independent", "talk", "advocacy"],
    verified: "2026-06"
  },
  {
    name: "Directions For Living",
    address: "1437 South Belcher Rd, Clearwater, FL 33764",
    phone: "727-524-4464",
    website: "https://www.directionsforliving.org",
    hours: "Vary by service line. See website.",
    fees: "Vary by service line.",
    summary: "Mental health and family services agency serving more than 12,000 people a year across Tampa Bay. Offers counseling, psychiatry, child safety services, homeless outreach, and support for families. Speaks English, Spanish, and ASL.",
    eligibility: "Varies by program.",
    intake: "Referrals or call for appointment.",
    tags: ["ese", "esol", "talk", "family", "medical"],
    verified: "2026-06"
  },
  {
    name: "Disability Achievement Center",
    address: "12552 Belcher Rd. South, Largo, FL 33773",
    phone: "727-539-7550",
    website: "https://www.mydacil.org",
    email: "info@mydacil.org",
    hours: "M-F 9:00 am to 5:00 pm",
    fees: "None",
    summary: "Center for Independent Living that helps people with disabilities of all ages and their families in Pinellas and Pasco. Offers information, advocacy, peer mentoring, independent living skills, job help, and a medical equipment recycling program.",
    eligibility: "Anyone with a disability.",
    intake: "Call, followed by a referral.",
    tags: ["ese", "reentry", "job", "independent", "advocacy", "family"],
    verified: "2026-06"
  },
  {
    name: "Division of Blind Services (DBS)",
    address: "1313 N. Tampa Street, Suite 106, Tampa, FL 33602",
    phone: "800-757-7190",
    website: "https://dbs.fldoe.org",
    hours: "M-F 8:00 am to 5:00 pm",
    fees: "None",
    summary: "Florida program for people who are blind or have low vision, from birth through adult. Offers early childhood help, school-age services like mobility training and assistive technology, and a paid School-to-Work Transition Program for older students. The Tampa District Office serves Pinellas County.",
    eligibility: "Bilateral visual impairment that creates a substantial impediment to learning, independence, or employment. Preferred: Social Security Number, legal U.S. status, six months Florida residency.",
    intake: "Call the Tampa district office.",
    tags: ["ese", "blind", "job", "learn", "independent", "transport"],
    verified: "2026-06"
  },
  {
    name: "FAAST - Florida Alliance for Assistive Services and Technology",
    address: "Central Regional Demonstration Center (at Tampa General Hospital), 2333 West Hillsborough Ave, Suite 140, Tampa, FL 33603",
    phone: "813-844-7591",
    website: "https://www.tgh.org/institutes-and-services/rehabilitation",
    email: "FAASTcen@tgh.org",
    hours: "M-F 8:30 am to 5:00 pm",
    fees: "None",
    summary: "Helps anyone with a disability access assistive technology. Offers free hands-on demonstrations, training, low-interest loans to buy devices, and a device lending library. The Central Regional Demonstration Center is hosted at Tampa General Hospital and serves Hillsborough, Manatee, and Pinellas counties. Statewide site: faast.org.",
    eligibility: "Anyone with a disability, or a caregiver or professional who serves them.",
    intake: "Call to schedule an appointment.",
    tags: ["ese", "independent", "advocacy"],
    verified: "2026-06"
  },
  {
    name: "Family Center on Deafness",
    address: "5175 45th St N, #9, St. Petersburg, FL 33714",
    phone: "727-501-2323",
    website: "https://www.fcdpinellas.org",
    email: "info@fcdpinellas.org",
    hours: "M-F 9:00 am to 5:00 pm",
    fees: "Varies",
    summary: "Pinellas non-profit for families with a Deaf or hard of hearing member. Offers peer support, family activities, mentoring, and a community for youth and parents from birth through high school. Serves mainly families and K-12 students.",
    eligibility: "Families with a Deaf or hard of hearing member in the Pinellas County School System. Serves from birth through high school to college transition.",
    intake: "Call 727-501-2323 for an appointment.",
    tags: ["ese", "deaf", "family", "talk"],
    verified: "2026-06"
  },
  {
    name: "Family Network on Disabilities (FND)",
    address: "311 S Missouri Ave, Clearwater, FL 33756",
    phone: "727-523-1130 or 800-825-5736",
    website: "https://www.FNDUSA.org",
    hours: "M-F 8:30 am to 4:30 pm",
    fees: "None",
    summary: "Florida-wide network for parents and advocates of children with disabilities, from birth to age 26. Free information, training, mentoring, and advocacy help. Speaks English, Spanish, and Creole. Serves mainly families and K-12 students.",
    eligibility: "Parents, guardians, and advocates of children from birth to age 26 with or suspected of disabilities.",
    intake: "Call for an appointment or visit the website.",
    tags: ["ese", "esol", "family", "advocacy"],
    verified: "2026-06"
  },
  {
    name: "Florida Diagnostic and Learning Resources System (FDLRS) Gulf Coast",
    address: "2929 County Road 193, Clearwater, FL 33759",
    phone: "727-793-2723",
    website: "https://www.fdlrsgulfcoast.org/",
    hours: "M-F 8:00 am to 4:00 pm",
    fees: "None",
    summary: "Florida-funded center that supports teachers and parents of children with disabilities in Pinellas, Pasco, and Hernando counties. Offers early childhood screening, teacher training, parent services, and assistive technology help for kids ages 3 to 22. Serves mainly families, teachers, and K-12 students.",
    eligibility: "Child Find: ages 3-5. Assistive Technology: ages 3-22 per student needs.",
    intake: "Call by telephone.",
    tags: ["family", "learn", "independent"],
    verified: "2026-06"
  },
  {
    name: "Goodwill Industries-Suncoast",
    address: "10596 Gandy Blvd., St. Petersburg, FL 33702",
    phone: "727-523-1512",
    website: "https://www.goodwill-suncoast.org",
    email: "powerofwork@goodwill-suncoast.com",
    hours: "M-F 8:00 am to 4:30 pm",
    fees: "Depends on program.",
    summary: "Helps people 16 and older with disabilities or other work barriers find jobs and learn job skills. Also offers affordable housing and support to live independently.",
    eligibility: "Age 16 or older with a disability.",
    intake: "Call or visit the website.",
    tags: ["ese", "reentry", "job", "learn", "independent"],
    verified: "2026-06"
  },
  {
    name: "LAUNCH at USF (formerly The Learning Academy)",
    address: "13301 Bruce B. Downs Blvd., MHC2113A, Tampa, FL 33612",
    phone: "813-974-2996 or 813-396-9211",
    website: "https://launch.cbcs.usf.edu/",
    email: "LASinfo@usf.edu",
    hours: "M-F 9:00 am to 5:00 pm",
    fees: "Private or Vocational Rehabilitation funding.",
    summary: "A career program at USF for young adults age 18 and older with autism (any high school diploma accepted). Offers internships, USF student mentors, parent workshops, and supported employment services. Formerly known as The Learning Academy.",
    eligibility: "Age 18+ with a high school diploma (all diplomas accepted) and a diagnosis on the autism spectrum.",
    intake: "Call to schedule an appointment.",
    tags: ["ese", "job", "learn", "autism"],
    verified: "2026-06"
  },
  {
    name: "Lighthouse of Pinellas",
    address: "6925 112th Circle North, Suite 103, Largo, FL 33773",
    phone: "727-544-4433",
    website: "https://www.lhpfl.org",
    hours: "M-F 8:00 am to 4:30 pm. Transition: Wednesdays 2:00-6:00 pm.",
    fees: "None for transition program.",
    summary: "Largo-based non-profit that has helped people who are blind or have low vision since 1956. The Transition Program (ages 14 to high school graduation) teaches job readiness, independent travel, assistive technology, and life skills. Free for eligible students.",
    eligibility: "Ages 14 to high school graduation, in middle or high school, with bilateral visual impairment, open with the Division of Blind Services.",
    intake: "Contact case manager for an appointment.",
    tags: ["ese", "blind", "job", "learn", "independent", "rec", "transport"],
    verified: "2026-06"
  },
  {
    name: "Operation PAR (Substance Abuse and Mental Health)",
    address: "6655 66th Street North, Pinellas Park, FL 33781",
    phone: "727-545-7564",
    intakePhone: "1-888-727-6398",
    website: "https://www.operationpar.org",
    email: "info@operpar.org",
    hours: "M-F 8:30 am to 5:30 pm, plus evenings and weekends as needed.",
    fees: "Sliding fee scale, insurance, co-payments.",
    summary: "Treatment center for substance use and mental health, including youth and families. Offers outpatient, intensive outpatient, and residential care. Uses a sliding-fee scale, insurance, or copays.",
    eligibility: "Level of care based on clinical need.",
    intake: "Call 1-888-PAR-NEXT for an assessment.",
    tags: ["esol", "reentry", "talk", "medical", "independent"],
    verified: "2026-06"
  },
  {
    name: "Pinellas County Schools Exceptional Student Education (ESE) Department",
    address: "301 4th Street SW, Largo, FL 33770",
    phone: "727-588-6032",
    website: "https://www.pcsb.org/ese",
    hours: "M-F 8:00 am to 4:30 pm",
    fees: "None",
    summary: "Pinellas County Schools department that coordinates services and transition planning for students with disabilities (ages 3 to 21). Help includes eligibility and services information, parent and family resources, transition planning, and specialized services like assistive technology, therapy, and hearing and vision support. Each high school has staff to help students plan for life after high school.",
    eligibility: "Students ages 3 to 21 with a disability or gifted needs.",
    intake: "Call the ESE Department at 727-588-6032, or ESE Parent Services at 727-588-6062.",
    tags: ["ese", "esol", "learn", "job", "family", "talk"],
    verified: "2026-06"
  },
  {
    name: "Pinellas Suncoast Transit Authority (PSTA)",
    address: "3201 Scherer Dr., St. Petersburg, FL 33716",
    phone: "727-540-1800",
    website: "https://www.psta.net",
    hours: "Service 7 days a week. Phone info Mon-Sat.",
    fees: "Local bus $2.00. Reduced disability fare $1.00. DART door-to-door $4.00. Transportation Disadvantaged monthly pass $8.25 for households below 150% poverty. Prices subject to change.",
    summary: "Pinellas County's public bus system. All buses are wheelchair accessible. Riders with disabilities get a reduced fare. DART is a shared door-to-door ride for people who can't ride a regular bus. Travel training is available.",
    eligibility: "Reduced fare for those with documented disability. DART for those who cannot access the accessible bus system.",
    intake: "Apply online or call to request an application.",
    tags: ["esol", "transport"],
    verified: "2026-06"
  },
  {
    name: "PlacementWorks, Inc.",
    address: "200 2nd Avenue South, St. Petersburg, FL 33701",
    phone: "727-798-4564",
    website: "https://www.placementworks.org",
    email: "Christy@PlacementWorks.com",
    hours: "M-F 8:00 am to 5:00 pm",
    fees: "None",
    summary: "Helps people with disabilities find and keep jobs. Services include job placement, on-the-job coaching, job-searching skills, and help negotiating workplace accommodations. Comes by referral from Vocational Rehabilitation, APD, or Social Security.",
    eligibility: "Referral via Vocational Rehabilitation or APD.",
    intake: "Upon receipt of referral.",
    tags: ["ese", "job"],
    verified: "2026-06"
  },
  {
    name: "Providing Advocacy and Recognizing Capabilities (PARC)",
    address: "3100 75th Street North, St. Petersburg, FL 33710-2919",
    phone: "727-345-9111",
    website: "https://www.parc-fl.org",
    hours: "Day Program: 7:30 am to 3:30 pm. Residential: 24 hours, 7 days.",
    fees: "Varies by service.",
    summary: "Long-running St. Pete non-profit for people with developmental disabilities. Offers job placement and coaching, residential housing for kids and adults, day programs in arts and recreation, technology training, and a children's program.",
    eligibility: "Children and adults with developmental disabilities.",
    intake: "Call for an appointment.",
    tags: ["ese", "esol", "job", "independent", "day", "rec", "family", "talk"],
    verified: "2026-06"
  },
  {
    name: "Ready for Life / Beyond Foster Care",
    address: "2300 Tall Pines Dr., #100, Largo, FL 33771",
    phone: "727-954-3989",
    website: "https://www.readyforlifepinellas.org",
    hours: "M-F 9:00 am to 5:00 pm, available 24/7 as needed.",
    fees: "None",
    summary: "Non-profit that helps youth ages 16 to 24 who are aging out of foster care. Connects youth to housing, education, jobs, and other community resources. Serves Pinellas and Pasco counties.",
    eligibility: "Youth ages 16-24 currently in or who have aged out of foster care in Pinellas or Pasco County.",
    intake: "Call or email.",
    tags: ["foster", "job", "learn", "independent", "money", "talk"],
    verified: "2026-06"
  },
  {
    name: "Abilities of Florida, A ServiceSource Affiliate",
    address: "2735 Whitney Rd., Clearwater, FL 33760",
    phone: "727-600-8923",
    website: "https://servicesource.org/abilities/",
    hours: "M-F 8:00 am to 4:30 pm",
    fees: "None",
    summary: "Abilities of Florida is a 501(c)(3) nonprofit organization that offers a variety of rehabilitation and employment services for people in the state of Florida with disabilities. Our programs include vocational evaluation and training, benefits planning, housing programs, and opportunities for self-employment.",
    eligibility: "Based on funder criteria (Vocational Rehabilitation, Able Trust).",
    intake: "Call for an appointment.",
    tags: ["ese", "esol", "job", "learn"],
    verified: "2026-06"
  },
  {
    name: "ServiceSource Work Incentives Planning and Assistance (WIPA)",
    address: "2735 Whitney Rd., Clearwater, FL 33760",
    phone: "727-538-7370",
    website: "https://www.servicesource.org",
    email: "WIPA.Referrals@servicesource.org",
    hours: "M-F 8:00 am to 4:30 pm",
    fees: "None",
    summary: "Free help for Social Security beneficiaries with disabilities (ages 14 to retirement) who want to work without losing benefits. Counselors help with planning, finding employment, and connecting to Vocational Rehabilitation or Employment Networks.",
    eligibility: "Social Security beneficiaries with disabilities, ages 14 to retirement.",
    intake: "Call for an appointment or email WIPA.Referrals@servicesource.org.",
    tags: ["ese", "esol", "job", "money", "advocacy"],
    verified: "2026-06"
  },
  {
    name: "Social Security Administration (SSA)",
    address: "Clearwater office: 2340 Drew Street, Clearwater, FL 33765. Multiple Florida locations, see website.",
    phone: "1-800-772-1213 (TTY 1-800-325-0778)",
    website: "https://www.socialsecurity.gov",
    hours: "Website 24/7. Phone Mon-Fri 7 am to 7 pm.",
    fees: "None",
    summary: "Federal agency that pays monthly cash benefits through two programs: SSDI for people who have worked and paid Social Security taxes, and SSI for people in financial need, including children with disabilities.",
    eligibility: "Varies by program. See website or call.",
    intake: "Apply online at socialsecurity.gov or call 1-800-772-1213.",
    tags: ["money"],
    verified: "2026-06"
  },
  {
    name: "Spanish Parent Helpline",
    address: "Pinellas County Schools ESOL Team",
    phone: "727-588-6445",
    website: null,
    hours: "7:00 am to 3:00 pm",
    fees: "None",
    summary: "Pinellas County Schools helpline for Spanish-speaking parents. Talk directly with a member of the ESOL team to find information about the school district. Serves mainly K-12 families.",
    eligibility: "Spanish-speaking parents and families.",
    intake: "Call the helpline.",
    tags: ["esol", "family"],
    verified: "2026-06"
  },
  {
    name: "Special Olympics Pinellas",
    address: "Special Olympics Florida, West Coast Region (Area 5), 313 W. Fletcher Avenue, Tampa, FL 33612. Serves Pinellas County.",
    phone: "386-569-3806",
    website: "https://www.specialolympicsflorida.org/westcoast",
    hours: "Sports run in seasons across the year. See website.",
    fees: "None",
    summary: "Year-round sports training and competition for children and adults age 8 and older with intellectual or developmental disabilities. Pinellas offers many sports across the year, including basketball, bocce, bowling, swimming, softball, pickleball, golf, and more.",
    eligibility: "Age 8 and older with intellectual or developmental disabilities. See website for full eligibility.",
    intake: "To join as an athlete or Unified partner, start at specialolympicsflorida.org/get-involved/athletes, or contact the Pinellas sports team: Ethan Michel (386-569-3806) or Liam Oxford (352-349-4869).",
    tags: ["ese", "rec"],
    verified: "2026-06"
  },
  {
    name: "The Arc Tampa Bay (formerly UPARC)",
    address: "1501 North Belcher Rd., Suite 249, Clearwater, FL 33765",
    phone: "727-799-3330",
    website: "https://www.thearctb.org",
    hours: "Day Programs M-F 8:00 am to 4:00 pm. Residential 24/7.",
    fees: "Varies. Rates established with APD, private pay available.",
    summary: "Supports people with intellectual and developmental disabilities. Three day-training programs, group homes, supported living, an apartment complex, and employment services. Includes some residential services for children ages 9 to 18.",
    eligibility: "Primarily adults with developmental disabilities. Residential services also for children ages 9-18. Employment services for all persons with disabilities.",
    intake: "Call the main number for an appointment.",
    tags: ["ese", "job", "day", "independent", "transport", "rec", "family"],
    verified: "2026-06"
  },
  {
    name: "Vocational Rehabilitation (VR)",
    address: "701 94th Avenue North, Suite 107, St. Petersburg, FL 33702",
    phone: "727-217-7930",
    website: "https://www.rehabworks.org",
    hours: "M-F 8:00 am to 5:00 pm",
    fees: "None",
    summary: "Florida state program that helps people with disabilities prepare for, find, and keep jobs. Free services include counseling, job placement, training, supported employment, physical or mental restoration, and transportation help.",
    eligibility: "Documented disability that significantly impedes employment (getting or keeping work).",
    intake: "Call for an appointment.",
    tags: ["ese", "esol", "reentry", "job", "learn", "transport", "talk", "medical"],
    verified: "2026-06"
  },
  {
    name: "CareAboutMe (Pinellas Mental Health Access)",
    address: "Serves Pinellas County. Call, text, or chat to find counseling.",
    phone: "1-888-431-1998 (call or text CARE)",
    website: "https://careaboutme.org",
    hours: "Mon-Fri 8:00 am to 10:00 pm, Saturday 10:00 am to 6:00 pm",
    fees: "Varies by provider; many offer a sliding scale.",
    summary: "Pinellas County program that helps residents find mental health and counseling services. Staff help find a match and schedule an appointment. Many providers in the network offer a sliding scale based on income.",
    eligibility: "Pinellas County residents seeking counseling or mental health support.",
    intake: "Call, text, or chat at 1-888-431-1998.",
    tags: ["talk", "family"],
    verified: "2026-06"
  },
  {
    name: "West Coast Behavioral Healthcare",
    address: "1751 1st Avenue North, St. Petersburg, FL 33713",
    phone: "727-471-8087",
    website: "https://westcoastbehavioral.com",
    email: "info@westcoastbehavioral.com",
    hours: "See website.",
    fees: "Sliding scale available.",
    summary: "Outpatient behavioral and mental health counseling serving St. Petersburg and Pinellas County. Individual counseling with sliding-scale options. Telehealth may be available.",
    eligibility: "Open to community members seeking counseling.",
    intake: "Call 727-471-8087 or email info@westcoastbehavioral.com.",
    tags: ["talk"],
    verified: "2026-06"
  },
  {
    name: "METRO Inclusive Health (Behavioral Health)",
    address: "Multiple St. Petersburg and Tampa Bay locations. Telehealth available.",
    phone: "727-321-3854",
    website: "https://metrotampabay.org/health/behavioral",
    hours: "See website.",
    fees: "Sliding scale and insurance accepted.",
    summary: "Behavioral health and psychiatry services with multiple St. Petersburg locations and telehealth. Inclusive, affirming care for the whole community, with sliding-scale options.",
    eligibility: "Open to community members seeking behavioral health care.",
    intake: "Schedule online or call 727-321-3854.",
    tags: ["talk", "medical"],
    verified: "2026-06"
  }
];

const NEED_LABELS = {
  // Populations
  ese: "Disability / ESE",
  esol: "Multilingual / ESOL",
  reentry: "Formerly incarcerated",
  foster: "Foster youth",
  // Services
  job: "Jobs &amp; training",
  learn: "Learning after high school",
  transport: "Getting around",
  independent: "Independent living",
  talk: "Counseling",
  medical: "Health care",
  money: "Money &amp; benefits",
  day: "Adult day programs",
  rec: "Recreation &amp; arts",
  family: "Family support",
  autism: "Autism support",
  deaf: "Deaf / hard of hearing",
  blind: "Blind / low vision",
  advocacy: "Advocacy &amp; rights"
};

const POPULATION_TAGS = new Set(["ese", "esol", "reentry", "foster"]);
