/* ============================================================
   Community Resources data + labels
   Agency information is drawn from the Pinellas Interagency Networking Council
   for Students (PINCS) Transition Services Resource Guide (Sept 2015).
   Last reviewed: 2026-05-13 (placeholder — see notes on each agency).
   To update an agency, edit it here. All spokes read from this file.
   ============================================================ */

const AGENCIES = [
        {
            name: "Agency for Persons with Disabilities (APD)",
            address: "1313 N Tampa Street, Suite 515, Tampa, FL 33602",
            phone: "813-233-4300",
            website: "https://www.apdcares.org",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "No charge or co-payment for services.",
            summary: "Florida state agency that helps people with developmental disabilities like autism, cerebral palsy, intellectual disabilities, Down syndrome, spina bifida, and Prader-Willi syndrome live, learn, and work in their community. Services are free.",
            eligibility: "Must live in Florida, be at least three years old, and have a developmental disability that occurred before age 18. Children at risk of being diagnosed may also be served.",
            intake: "Download an application from apdcares.org or contact the APD regional office.",
            tags: ["ese", "job", "learn", "transport", "independent", "talk", "medical", "day", "rec", "family", "autism"],
            verified: "2015-09"
        },
        {
            name: "All Children's Hospital - Johns Hopkins Medicine",
            address: "Autism Center / Pediatric Developmental Medicine, St. Petersburg, FL",
            phone: "727-767-2886",
            website: "https://www.allkids.org",
            hours: "M-F 8:00 am to 4:00 pm",
            fees: "CMS, private insurance, private pay.",
            summary: "Hospital programs that diagnose and treat autism (ages birth to 10) and other developmental conditions including learning disabilities, ADHD, motor delays, and developmental delays (ages birth to 15). Takes insurance, CMS, and private pay.",
            eligibility: "Birth to age 15 depending on program.",
            intake: "Call for an appointment or request one at allkids.org under 'Services Not Listed'.",
            tags: ["ese", "esol", "medical", "talk", "family", "autism"],
            verified: "2015-09"
        },
        {
            name: "Boley Centers, Inc.",
            address: "Pinellas, Hillsborough, and Manatee Counties",
            phone: "727-821-4819",
            website: "https://www.boleycenters.org",
            hours: "M-F 8:30 am to 4:30 pm",
            fees: "Based on income. Medicare and Medicaid accepted.",
            summary: "Non-profit that helps people living with mental illness, homelessness, or other barriers in Pinellas, Hillsborough, and Manatee counties. Offers job training, supported jobs, housing, and case management.",
            eligibility: "Evaluations required for clients with disabilities.",
            intake: "Call admissions at 727-499-2352.",
            tags: ["ese", "reentry", "job", "independent", "talk", "advocacy"],
            verified: "2015-09"
        },
        {
            name: "CareerSource Pinellas (Ticket to Work)",
            address: "Clearwater, Tarpon Springs, and St. Petersburg locations",
            phone: "727-524-4344",
            website: "https://www.careersourcepinellas.com",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "None",
            summary: "Pinellas County's main workforce center for job seekers. Helps people with disabilities find jobs, learn job skills, attend job fairs, and use Social Security's Ticket to Work program. Services are free.",
            eligibility: "Disabled workers entering or returning to the workforce. Ticket to Work or WIA eligibility needed for vocational or post-secondary training.",
            intake: "Call for an appointment.",
            tags: ["ese", "reentry", "job", "learn"],
            verified: "2015-09"
        },
        {
            name: "Center for Autism and Related Disabilities (CARD-USF)",
            address: "13301 Bruce B. Downs Blvd., Tampa, FL 33612",
            phone: "800-333-4530",
            website: "http://card-usf.fmhi.usf.edu",
            hours: "M-F 8:30 am to 5:00 pm",
            fees: "None",
            summary: "Free help for people with autism and related disabilities, their families, and the teachers and professionals who work with them. Offers training, coaching, and one-on-one consultation. Based at USF.",
            eligibility: "Diagnosis of Autism Spectrum Disorder or related disability (including dual sensory impairment).",
            intake: "Call for an appointment.",
            tags: ["ese", "esol", "autism", "family", "talk"],
            verified: "2015-09"
        },
        {
            name: "Creative Clay",
            address: "1114 Central Avenue, St. Petersburg, FL",
            phone: "727-825-0515",
            website: "https://www.creativeclay.org",
            hours: "Call for hours",
            fees: "Varies",
            summary: "Art studio in St. Pete for artists with developmental, physical, or emotional disabilities. Offers art classes, vocational training, summer camps for kids, and a gallery where members sell their work. Open to adults and youth ages 6 to 22.",
            eligibility: "Varies by program. Includes adults with disabilities and youth ages 6-22.",
            intake: "Telephone for instructions.",
            tags: ["ese", "job", "learn", "rec", "day"],
            verified: "2015-09"
        },
        {
            name: "Crisis Center of Tampa Bay",
            address: "One Crisis Center Plaza, Tampa, FL 33613",
            phone: "211",
            website: "https://www.crisiscenter.com",
            hours: "24 hours a day, 365 days a year",
            fees: "None",
            summary: "Free 24-hour help for anyone in a crisis. Call 211 for help with abuse, domestic violence, money problems, substance abuse, medical emergencies, or thoughts of suicide.",
            eligibility: "Anyone in crisis.",
            intake: "Call the 211 crisis hotline.",
            tags: ["talk"],
            verified: "2015-09"
        },
        {
            name: "Department of Juvenile Justice (Probation and Community Intervention)",
            address: "955 26th Street South, St. Petersburg, FL 33712",
            phone: "727-893-2077",
            website: "http://www.djj.state.fl.us/Probation/index.html",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "Varies with type of service.",
            summary: "For youth under 18 who have been charged with a crime in Pinellas County. Offers prevention, intervention, and residential programs based on a youth assessment.",
            eligibility: "Youth under age 18 charged with a law violation in Pinellas County.",
            intake: "Agency will notify family.",
            tags: ["reentry", "independent", "talk", "advocacy"],
            verified: "2015-09"
        },
        {
            name: "Directions For Living",
            address: "1437 South Belcher Rd, Clearwater, FL 33764",
            phone: "727-524-4464",
            website: "http://www.directionsforliving.org",
            hours: "Vary by service line. See website.",
            fees: "Vary by service line.",
            summary: "Mental health and family services agency serving more than 12,000 people a year across Tampa Bay. Offers counseling, psychiatry, child safety services, homeless outreach, and support for families. Speaks English, Spanish, and ASL.",
            eligibility: "Varies by program.",
            intake: "Referrals or call for appointment.",
            tags: ["ese", "esol", "talk", "family", "medical"],
            verified: "2015-09"
        },
        {
            name: "Disability Achievement Center",
            address: "12552 Belcher Rd. South, Largo, FL 33773",
            phone: "727-539-7550",
            website: "https://www.disabilityachievementcenter.org",
            hours: "M-F 9:00 am to 5:00 pm",
            fees: "None",
            summary: "Non-profit that helps people with disabilities of all ages and their families in Pinellas and Pasco. Offers information, advocacy, peer mentoring, independent living skills, job help, and a medical equipment recycling program.",
            eligibility: "Anyone with a disability.",
            intake: "Call, followed by a referral.",
            tags: ["ese", "reentry", "job", "independent", "advocacy", "family"],
            verified: "2015-09"
        },
        {
            name: "Division of Blind Services (DBS)",
            address: "415 S. Armenia Avenue, Tampa, FL 33609",
            phone: "813-871-7190",
            website: "http://dbs.myflorida.com/index.php",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "None",
            summary: "Florida program for people who are blind or visually impaired, from birth through adult. Offers early childhood help, school-age services like mobility training and assistive technology, and a paid School-to-Work Transition Program for older students.",
            eligibility: "Bilateral visual impairment that creates a substantial impediment to learning, independence, or employment. Preferred: Social Security Number, legal U.S. status, six months Florida residency.",
            intake: "Call the district office.",
            tags: ["ese", "blind", "job", "learn", "independent", "transport"],
            verified: "2015-09"
        },
        {
            name: "Raising Down Syndrome Foundation",
            address: "Pinellas County, FL",
            phone: null,
            website: "http://www.raisingDS.com",
            email: "info@raisingDS.com",
            hours: null,
            fees: null,
            summary: "Pinellas County non-profit that supports families of children and adults with Down syndrome through outreach, support, and education.",
            eligibility: "Families affected by Down Syndrome.",
            intake: "Email info@raisingDS.com.",
            tags: ["ese", "family"],
            verified: "2015-09"
        },
        {
            name: "FAAST - Florida Alliance for Assistive Services and Technology",
            address: "Tampa General Rehabilitation Center, 6 Tampa General Circle, Room 214, Tampa, FL 33606",
            phone: "813-844-7591",
            website: "http://www.faast.org/",
            hours: "M-F 8:30 am to 5:00 pm",
            fees: "None",
            summary: "Helps anyone with a disability access assistive technology. Offers free hands-on demonstrations, training, low-interest loans to buy devices, and a device lending library.",
            eligibility: "Anyone with a disability, or a caregiver or professional who serves them.",
            intake: "Call to schedule an appointment.",
            tags: ["ese", "independent", "advocacy"],
            verified: "2015-09"
        },
        {
            name: "Family Center on Deafness",
            address: "12445 62nd St, #303, Largo, FL 33773",
            phone: "727-648-4968",
            website: "https://www.fcdpinellas.org",
            hours: "M-F 9:00 am to 5:00 pm",
            fees: "Varies",
            summary: "Pinellas non-profit for families with a deaf or hard-of-hearing member. Offers peer support, family activities, mentoring, and a community for youth and parents from birth through high school.",
            eligibility: "Families with a deaf or hard of hearing member in the Pinellas County School System. Serves from birth through high school to college transition.",
            intake: "Call 727-549-6664 for an appointment.",
            tags: ["ese", "deaf", "family", "talk"],
            verified: "2015-09"
        },
        {
            name: "Family Network on Disabilities (FND)",
            address: "2196 Main St., Suite K, Dunedin, FL 34698",
            phone: "727-523-1130",
            website: "https://www.FNDUSA.org",
            hours: "M-F 8:30 am to 4:30 pm",
            fees: "None",
            summary: "Florida-wide network for parents and advocates of children with disabilities, from birth to age 26. Free information, training, mentoring, and advocacy help. Speaks English, Spanish, and Creole.",
            eligibility: "Parents, guardians, and advocates of children from birth to age 26 with or suspected of disabilities.",
            intake: "Call for an appointment or visit the website.",
            tags: ["ese", "esol", "family", "advocacy"],
            verified: "2015-09"
        },
        {
            name: "Florida Diagnostic and Learning Resources System (FDLRS) Gulf Coast",
            address: "2929 County Road 193, Clearwater, FL 33759",
            phone: "727-793-2723",
            website: "https://www.pcsb.org",
            hours: "M-F 8:00 am to 4:30 pm",
            fees: "None",
            summary: "Florida-funded center that supports teachers and parents of children with disabilities in Pinellas, Pasco, and Hernando counties. Offers early childhood screening, teacher training, parent services, and assistive technology help for kids ages 3 to 22.",
            eligibility: "Child Find: ages 3-5. Assistive Technology: ages 3-22 per student needs.",
            intake: "Call by telephone.",
            tags: ["family", "learn", "independent"],
            verified: "2015-09"
        },
        {
            name: "Goodwill Industries-Suncoast",
            address: "10596 Gandy Blvd., St. Petersburg, FL 33702",
            phone: "727-523-1512",
            website: "https://www.goodwill-suncoast.org",
            hours: "M-F 8:00 am to 4:30 pm",
            fees: "Depends on program.",
            summary: "Helps people 16 and older with disabilities or other work barriers find jobs and learn job skills. Also offers affordable housing and support to live independently.",
            eligibility: "Age 16 or older with a disability.",
            intake: "Call or visit the website.",
            tags: ["ese", "reentry", "job", "learn", "independent"],
            verified: "2015-09"
        },
        {
            name: "Learning Academy at USF",
            address: "13301 Bruce B. Downs Blvd., MHC2113A, Tampa, FL 33606",
            phone: "813-974-2996",
            website: "http://card-usf.fmhi.usf.edu/LearnAcademy.asp",
            hours: "M-F 8:30 am to 5:00 pm",
            fees: "Private or Vocational Rehabilitation funding.",
            summary: "A two-semester career program at USF for young adults age 18 and older with autism (any high school diploma accepted). Offers internships, USF student mentors, parent workshops, and supported employment services.",
            eligibility: "Age 18+ with a high school diploma (all diplomas accepted) and a diagnosis on the autism spectrum.",
            intake: "Call to schedule an appointment.",
            tags: ["ese", "job", "learn", "autism"],
            verified: "2015-09"
        },
        {
            name: "Lighthouse of Pinellas",
            address: "6925 112th Circle North, Suite 103, Largo, FL 33773",
            phone: "727-544-4433 ext. 258",
            website: "https://www.lhpfl.org",
            hours: "M-F 8:00 am to 4:30 pm. Transition: Wednesdays 2:00-6:00 pm.",
            fees: "None for transition program.",
            summary: "Largo-based non-profit that has helped blind and visually impaired people since 1956. The Transition Program (ages 14 to 22) teaches job readiness, independent travel, assistive technology, and life skills. Free for eligible students.",
            eligibility: "Ages 14-22 in middle or high school with bilateral visual impairment, open with the Division of Blind Services.",
            intake: "Contact case manager for an appointment.",
            tags: ["ese", "blind", "job", "learn", "independent", "rec", "transport"],
            verified: "2015-09"
        },
        {
            name: "Operation PAR (Substance Abuse and Mental Health)",
            address: "6655 66th Street, Pinellas Park, FL 33781",
            phone: "727-545-7564",
            website: "https://www.operationpar.org",
            hours: "M-F 8:30 am to 5:30 pm, plus evenings and weekends as needed.",
            fees: "Sliding fee scale, insurance, co-payments.",
            summary: "Treatment center for substance abuse and mental health, including youth and families. Offers outpatient, intensive outpatient, and residential care. Uses a sliding-fee scale, insurance, or copays.",
            eligibility: "Level of care based on clinical need.",
            intake: "Call 1-888-PAR-NEXT for an assessment.",
            tags: ["esol", "reentry", "talk", "medical", "independent"],
            verified: "2015-09"
        },
        {
            name: "Pinellas County Schools Exceptional Student Education (ESE) Department",
            address: "301 4th Street SW, Largo, FL 33770",
            phone: "727-588-6032",
            website: "https://www.pcsb.org",
            hours: "M-F 8:00 am to 4:30 pm",
            fees: "None",
            summary: "Pinellas County Schools department that coordinates transition services for students with disabilities. Each high school has staff to help students plan for life after high school.",
            eligibility: "Students with a disability.",
            intake: "Telephone the office.",
            tags: ["ese", "esol", "learn", "job", "family", "talk"],
            verified: "2015-09"
        },
        {
            name: "Pinellas Suncoast Transit Authority (PSTA)",
            address: "3201 Scherer Dr., St. Petersburg, FL 33716",
            phone: "727-540-1800",
            website: "https://www.psta.net",
            hours: "Service 7 days a week. Phone info Mon-Sat.",
            fees: "Local bus $2.00. Reduced disability fare $1.00. DART door-to-door $4.00. Transportation Disadvantaged monthly pass $8.25 for households below 150% poverty. Prices subject to change.",
            summary: "Pinellas County's public bus system. All buses are wheelchair accessible. Riders with disabilities get a reduced fare. DART is a shared door-to-door ride for people who can't ride a regular bus. Travel training is available.",
            eligibility: "Reduced fare for those with documented disability. DART for those who cannot access the accessible bus system.",
            intake: "Apply online or call to request an application.",
            tags: ["esol", "transport"],
            verified: "2015-09"
        },
        {
            name: "Pinellas Technical College",
            address: "St. Pete: 901 34th Street S, St. Petersburg, FL 33711. Clearwater: 6100 154th Avenue N, Clearwater, FL 33760.",
            phone: "St. Pete: 727-893-2500 ext. 2520. Clearwater: 727-538-7167 ext. 2006.",
            website: "https://www.myptc.edu",
            hours: "Guidance, Bookstore, Records: M-Th 7:00 am-6:30 pm; Fri 7:00 am-noon. Financial Aid: M-Th 7:00 am-3:00 pm; Fri 7:00 am-noon.",
            fees: "State tuition. $15 application fee plus per-program fees.",
            summary: "Career and technical college with campuses in St. Petersburg and Clearwater. Over 40 career programs plus continuing education. Students with documented disabilities can request classroom accommodations through Student Services.",
            eligibility: "Students with documented disability.",
            intake: "Present documentation to the campus Student Services department.",
            tags: ["ese", "esol", "learn", "job", "money"],
            verified: "2015-09"
        },
        {
            name: "PlacementWorks, Inc.",
            address: "15 Eighth Street North, St. Petersburg, FL 33701",
            phone: "727-798-4564",
            website: "https://www.placementworks.com",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "None",
            summary: "Helps people with disabilities find and keep jobs. Services include job placement, on-the-job coaching, job-searching skills, and help negotiating workplace accommodations. Comes by referral from Vocational Rehabilitation, APD, or Social Security.",
            eligibility: "Referral via Vocational Rehabilitation or APD.",
            intake: "Upon receipt of referral.",
            tags: ["ese", "job"],
            verified: "2015-09"
        },
        {
            name: "Project 10 Transition Education Network",
            address: "USF St. Petersburg, 140 7th Avenue South, SVB112, St. Petersburg, FL 33701",
            phone: "727-873-4661",
            website: "http://www.project10.info/",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "Grant through FLDOE-BEESS",
            summary: "Provides Florida school districts with training, professional development, and resources to help students with disabilities transition from school to adult life. Based at USF St. Pete. Works through school district ESE departments.",
            eligibility: "Provides technical assistance, training, professional development, and resources to school districts.",
            intake: "Works through the school district ESE department.",
            tags: ["ese", "learn", "job", "advocacy"],
            verified: "2015-09"
        },
        {
            name: "Providing Advocacy and Recognizing Capabilities (PARC)",
            address: "3190 Tyrone Blvd. North, St. Petersburg, FL 33710",
            phone: "727-345-9111",
            website: "https://www.parc-fl.org",
            hours: "Day Program: 7:30 am to 3:30 pm. Residential: 24 hours, 7 days.",
            fees: "Varies by service.",
            summary: "Long-running St. Pete non-profit for people with developmental disabilities. Offers job placement and coaching, residential housing for kids and adults, day programs in arts and recreation, technology training, and a children's program.",
            eligibility: "Children and adults with developmental disabilities.",
            intake: "Call for an appointment.",
            tags: ["ese", "esol", "job", "independent", "day", "rec", "family", "talk"],
            verified: "2015-09"
        },
        {
            name: "Ready for Life / Beyond Foster Care",
            address: "300 31st Street North, Suite 565, St. Petersburg, FL 33713",
            phone: "727-631-1778",
            website: "https://www.readyforlifepinellas.org",
            hours: "M-F 9:00 am to 5:00 pm, available 24/7 as needed.",
            fees: "None",
            summary: "Non-profit that helps youth ages 16 to 24 who are aging out of foster care in Pinellas County. Connects youth to housing, education, jobs, and other community resources.",
            eligibility: "Youth ages 16-24 currently in or who have aged out of foster care in Pinellas County.",
            intake: "Call or email.",
            tags: ["foster", "job", "learn", "independent", "money", "talk"],
            verified: "2015-09"
        },
        {
            name: "SEDNET / Pinellas",
            address: "Pinellas County School Board, 301 4th Street SW, Largo, FL 33770",
            phone: "727-660-1220 ext. 2024",
            website: "http://www.sednetfl.info",
            hours: "M-F 8:00 am to 3:30 pm",
            fees: "Not applicable",
            summary: "Network that helps students with emotional or behavioral challenges in Pinellas County Schools. Coordinates between schools, families, and agencies, and provides cross-agency training for ages PreK to 12.",
            eligibility: "Students with or at risk of emotional and behavioral challenges.",
            intake: "Not applicable.",
            tags: ["ese", "talk", "family", "learn"],
            verified: "2015-09"
        },
        {
            name: "ServiceSource (formerly Abilities, Inc. of Florida)",
            address: "2735 Whitney Rd., Clearwater, FL 33760",
            phone: "727-600-8920",
            website: "https://www.servicesource.org",
            hours: "M-F 8:00 am to 4:30 pm",
            fees: "None",
            summary: "Non-profit that helps people with disabilities find work. Offers vocational evaluation, pre-employment training, job placement, and a STEM career exploration program (High School/High Tech) for older students.",
            eligibility: "Based on funder criteria (Vocational Rehabilitation, Able Trust).",
            intake: "Call for an appointment.",
            tags: ["ese", "esol", "job", "learn"],
            verified: "2015-09"
        },
        {
            name: "ServiceSource Work Incentives Planning and Assistance (WIPA)",
            address: "2735 Whitney Rd., Clearwater, FL 33760",
            phone: "727-600-8923",
            website: "https://www.servicesource.org",
            hours: "M-F 8:00 am to 4:30 pm",
            fees: "None",
            summary: "Free help for Social Security beneficiaries with disabilities (ages 14 to retirement) who want to work without losing benefits. Counselors help with planning, finding employment, and connecting to Vocational Rehabilitation or Employment Networks.",
            eligibility: "Social Security beneficiaries with disabilities, ages 14 to retirement.",
            intake: "Call for an appointment.",
            tags: ["ese", "esol", "job", "money", "advocacy"],
            verified: "2015-09"
        },
        {
            name: "Social Security Administration (SSA)",
            address: "Multiple locations. See website.",
            phone: "1-800-772-1213 (TTY 1-800-325-0778)",
            website: "https://www.socialsecurity.gov",
            hours: "Website 24/7. Phone Mon-Fri 7 am to 7 pm.",
            fees: "None",
            summary: "Federal agency that pays monthly cash benefits through two programs: SSDI for people who have worked and paid Social Security taxes, and SSI for people in financial need, including children with disabilities.",
            eligibility: "Varies by program. See website or call.",
            intake: "Apply online at socialsecurity.gov or call 1-800-772-1213.",
            tags: ["money"],
            verified: "2015-09"
        },
        {
            name: "Spanish Parent Helpline",
            address: "Pinellas County Schools ESOL Team",
            phone: "727-623-4414",
            website: null,
            hours: "7:00 am to 3:00 pm",
            fees: "None",
            summary: "Pinellas County Schools helpline for Spanish-speaking parents. Talk directly with a member of the ESOL team to find information about the school district.",
            eligibility: "Spanish-speaking parents and families.",
            intake: "Call the helpline.",
            tags: ["esol", "family"],
            verified: "2015-09"
        },
        {
            name: "Special Olympics Pinellas",
            address: "Pinellas County, FL",
            phone: "727-669-1220 ext. 2008",
            website: "https://specialolympicsflorida.org/pinellas/",
            hours: "8:00 am to 3:30 pm",
            fees: null,
            summary: "Year-round sports training and competition for children and adults age 8 and older with intellectual or developmental disabilities. Serves over 980 athletes in Pinellas County across 13 different sports.",
            eligibility: "Age 8 and older with intellectual or developmental disabilities. See website for full eligibility.",
            intake: "See website.",
            tags: ["ese", "rec"],
            verified: "2015-09"
        },
        {
            name: "St. Petersburg College (SPC) Disability Resources",
            address: "Multiple campuses across Pinellas County",
            phone: "Clearwater 727-791-2710. St. Pete/Gibbs 727-341-4316. EpiCenter/Downtown 727-341-7913.",
            website: "http://www.spcollege.edu/dr",
            hours: "M-Th 8:30 am to 7:00 pm; Fri 8:30 am to 12:00 pm.",
            fees: "State tuition. No fee for Disability Resources services.",
            summary: "Open-enrollment state college offering AA, AS, BAS, and BS degrees, plus certificates. Students with documented disabilities can request classroom accommodations through Disability Resources at any campus.",
            eligibility: "SPC students with documented disability.",
            intake: "Present documentation to campus Disability Resources Managers.",
            tags: ["ese", "learn"],
            verified: "2015-09"
        },
        {
            name: "Sunrise Community, Inc.",
            address: "Adult Day Training: 1401 5th Avenue North, St. Petersburg, FL 33710. Residential: 1101 102nd Avenue North, St. Petersburg, FL 33716.",
            phone: "Day Training 727-896-7117. Residential 727-576-0492.",
            website: "https://www.sunrisegroup.org",
            hours: "M-F 8:30 am to 3:30 pm.",
            fees: "Varies. Medicaid waiver and private pay.",
            summary: "Provides skilled nursing, respite care, residential housing, and adult day training in St. Petersburg. Day training (age 22 and up) includes computer training, socialization, adaptive equipment use, and personal care. Accepts Medicaid waiver and private pay.",
            eligibility: "Individuals with disabilities ages 22 and up, severe or profound intellectual or physical disabilities.",
            intake: "Complete an application and interview with the individual or parent/guardian.",
            tags: ["ese", "esol", "day", "independent", "medical"],
            verified: "2015-09"
        },
        {
            name: "The Arc Tampa Bay (formerly UPARC)",
            address: "1501 North Belcher Rd., Suite 249, Clearwater, FL 33765",
            phone: "727-799-3330",
            website: "https://www.thearctb.org",
            hours: "Day Programs M-F 8:00 am to 4:00 pm. Residential 24/7.",
            fees: "Varies. Rates established with APD, private pay available.",
            summary: "Supports people with intellectual and developmental disabilities. Three day-training programs, group homes, supported living, an apartment complex, and employment services. Includes some residential services for children ages 9 to 18.",
            eligibility: "Primarily adults with developmental disabilities. Residential services also for children ages 9-18. Employment services for all persons with disabilities.",
            intake: "Call the main number for an appointment.",
            tags: ["ese", "job", "day", "independent", "transport", "rec", "family"],
            verified: "2015-09"
        },
        {
            name: "VSA Florida (Very Special Arts)",
            address: "4201 USF Willow Drive, FAO 179, Tampa, FL 33620",
            phone: "813-974-0721",
            website: "https://www.vsafl.org",
            hours: "M-F 7:00 am to 1:00 am; Sat-Sun 10:00 am to 10:00 pm.",
            fees: null,
            summary: "Professional development for teachers on inclusive arts learning. Offers workshops statewide, regionally, and locally, plus art residencies that model inclusion strategies for any classroom.",
            eligibility: "Students in Pinellas County Schools.",
            intake: "Call for an appointment.",
            tags: ["ese", "rec", "learn", "family"],
            verified: "2015-09"
        },
        {
            name: "Vocational Rehabilitation (VR)",
            address: "701 94th Avenue North, Suite 107, St. Petersburg, FL 33702",
            phone: "727-217-7930",
            website: "https://www.rehabworks.org",
            hours: "M-F 8:00 am to 5:00 pm",
            fees: "None",
            summary: "Florida state program that helps people with disabilities prepare for, find, and keep jobs. Free services include counseling, job placement, training, supported employment, physical or mental restoration, and transportation help.",
            eligibility: "Documented disability that significantly impedes employment (getting or keeping work).",
            intake: "Call for an appointment.",
            tags: ["ese", "esol", "reentry", "job", "learn", "transport", "talk", "medical"],
            verified: "2015-09"
        },
        {
            name: "Williams Syndrome Association",
            address: "Pinellas County, FL",
            phone: "727-424-0101 (toll free 800-806-1871)",
            website: "https://www.williams-syndrome.org",
            hours: "M-F 9:00 am to 5:00 pm",
            fees: "Minimal fees or scholarships available.",
            summary: "National organization that supports individuals and families affected by Williams syndrome through education, advocacy, and research.",
            eligibility: "Teachers, parents, students, volunteers, and anyone interested in Williams Syndrome.",
            intake: "Call.",
            tags: ["ese", "family", "medical", "rec"],
            verified: "2015-09"
        },
        {
            name: "ZVRS - Z Video Relay Services",
            address: "600 Cleveland Street, Suite 1000, Clearwater, FL 33755",
            phone: "727-254-5600",
            website: "https://www.zvrs.com",
            hours: "M-F 7:00 am to 1:00 am; Sat-Sun 10:00 am to 10:00 pm.",
            fees: "Varies",
            summary: "Free video relay service that lets people who are deaf or hard of hearing have phone conversations with hearing people. Uses a videophone and a certified interpreter.",
            eligibility: "Deaf and hard of hearing.",
            intake: "By telephone.",
            tags: ["ese", "esol", "deaf"],
            verified: "2015-09"
        }
    ];

const NEED_LABELS = {
        // Populations
        ese: "Disability / ESE",
        esol: "Multilingual / ESOL",
        reentry: "Returning citizens",
        foster: "Foster youth",
        // Services
        job: "Jobs &amp; training",
        learn: "Learning after high school",
        transport: "Getting around",
        independent: "Independent living",
        talk: "Counseling",
        medical: "Health care",
        money: "Money &amp; benefits",
        day: "Day programs",
        rec: "Recreation &amp; arts",
        family: "Family support",
        autism: "Autism support",
        deaf: "Deaf / hard of hearing",
        blind: "Blind / low vision",
        advocacy: "Advocacy"
    };

const POPULATION_TAGS = new Set(["ese", "esol", "reentry", "foster"]);
